### ISSUE TITLE
Leer archivos en OSADA - Bloques

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#536]
Buenas, estuve leyendo los issues (que de hecho me sirvieron un montón para sacar otras dudas que tenía), pero esta duda en particular no la leí...
Supongamos que un archivo ocupa los bloques 2, 4, 10 y 17.
Sacando el bloque 2 y el bloque 17... ¿El archivo ocupa enteros los bloques 4 y 10? ¿O puede ocurrir que un archivo ocupe la mitad de cada uno de los bloques?

Gracias!
Saludos

**Comment by sciciliani** [comment]
Para el filesystem el archivo ocupa los 4 bloques.

Luego con el tamaño vos podes determinar que es relevante solo una fracción
del último bloque.

A tu pregunta concreta, no, no puede ocupar bloques de manera parcial.

El 30/10/2016 22:33, "fpatalagoity" <notifications@github.com> escribió:

Buenas, estuve leyendo los issues (que de hecho me sirvieron un montón para
sacar otras dudas que tenía), pero esta duda en particular no la leí...
Supongamos que un archivo ocupa los bloques 2, 4, 10 y 17.
Sacando el bloque 2 y el bloque 17... ¿El archivo ocupa enteros los bloques
4 y 10? ¿O puede ocurrir que un archivo ocupe la mitad de cada uno de los
bloques?

Gracias!
Saludos

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sisoputnfrba/foro/issues/536>, or mute the thread

**Comment by fpatalagoity** [comment]
Gracias!
